name = "eye-void"
author = "it-tfarrkira"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe4280c3dfd5a4e8505f234661dc46a22f224559ca5db86d27c3dd5746022b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
