name = "eye-void"
author = "it-tfarrkira"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d56bc2f6e008cc85e671facb7dc24d83913df7cdb076c91ac2c8d4f67a6c35e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
