name = "eye-void"
author = "it-tfarrkira"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0a08d5f617e3a6e0810823ef2db0ae2b291f8f05d1ac5cc04d107ae99bd173b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
